---
- name: Nginx Health Check
  hosts: all
  become: yes

  tasks:
    - name: Check nginx service state
      ansible.builtin.systemd:
        name: nginx
      register: nginx_status

    - name: Show status
      ansible.builtin.debug:
        var: nginx_status.status.ActiveState

    - name: Fail if nginx not running
      ansible.builtin.fail:
        msg: "Nginx is not running!"
      when: nginx_status.status.ActiveState != "active"
      