---
- hosts: all
  become: yes

  tasks:
    - name: Deploy custom nginx index page
      template:
        src: index.html.j2
        dest: /usr/share/nginx/html/index.html
        mode: '0644'
